#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 12 11:00:01 CET 2023
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim FSM_VGA_TB_func_synth -key {Post-Synthesis:sim_1:Functional:FSM_VGA_TB} -tclbatch FSM_VGA_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim FSM_VGA_TB_func_synth -key {Post-Synthesis:sim_1:Functional:FSM_VGA_TB} -tclbatch FSM_VGA_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

